//
//  LoginInteractor.swift
//  CleanSwift(VIP)
//
//  Created by Steve JobsOne on 4/14/20.
//  Copyright (c) 2020 Steve JobsOne. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogicDelegate {
    func loginRequestWith(request: Login.Request)
}

protocol LoginDataStoreDelegate {
    //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogicDelegate, LoginDataStoreDelegate {
    var presenterDelegate: LoginPresentationLogicDelegate?
    var worker: LoginWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func loginRequestWith(request: Login.Request) {
        worker = LoginWorker()
        
        worker?.loginWith(request: request){ [weak self] error in
            
            if let strongSelf = self{
                
                if  (error != nil){
                    let response = Login.Response(success: false)
                    strongSelf.presenterDelegate?.login(response: response)
                }else{
                    let response = Login.Response(success: true)
                    strongSelf.presenterDelegate?.login(response: response)
                }
            }
        }
        
    }
}
