//
//  ProjectListRouter.swift
//  CleanSwift(VIP)
//
//  Created by Steve JobsOne on 4/18/20.
//  Copyright (c) 2020 Steve JobsOne. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProjectListRoutingLogicDelegate {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ProjectListDataPassingDelegate {
  var dataStore: ProjectListDataStoreDelegate? { get }
}

class ProjectListRouter: NSObject, ProjectListRoutingLogicDelegate, ProjectListDataPassingDelegate {
  weak var viewController: ProjectListViewController?
  var dataStore: ProjectListDataStoreDelegate?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: ProjectListViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: ProjectListDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
