//
//  ProjectListViewController.swift
//  CleanSwift(VIP)
//
//  Created by Steve JobsOne on 4/18/20.
//  Copyright (c) 2020 Steve JobsOne. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProjectListDisplayLogicDelegate: class {
  func displaySomething(viewModel: ProjectList.Something.ViewModel)
}

class ProjectListViewController: UIViewController, ProjectListDisplayLogicDelegate {
  var interactorDelegate: ProjectListBusinessLogicDelegate?
  var routerDelegate: (NSObjectProtocol & ProjectListRoutingLogicDelegate & ProjectListDataPassingDelegate)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup() {
    let viewController = self
    let interactor = ProjectListInteractor()
    let presenter = ProjectListPresenter()
    let router = ProjectListRouter()
    viewController.interactorDelegate = interactor
    viewController.routerDelegate = router
    interactor.presenterDelegate = presenter
    presenter.viewControllerDelegate = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = routerDelegate, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething() {
    let request = ProjectList.Something.Request()
    interactorDelegate?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: ProjectList.Something.ViewModel) {
    //nameTextField.text = viewModel.name
    
    //print
    
  }
}
