//
//  ProjectListPresenter.swift
//  CleanSwift(VIP)
//
//  Created by Steve JobsOne on 4/18/20.
//  Copyright (c) 2020 Steve JobsOne. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProjectListPresentationLogicDelegate {
  func presentSomething(response: ProjectList.Something.Response)
}

class ProjectListPresenter: ProjectListPresentationLogicDelegate {
  weak var viewControllerDelegate: ProjectListDisplayLogicDelegate?
  
  // MARK: Do something
  
  func presentSomething(response: ProjectList.Something.Response) {
    let viewModel = ProjectList.Something.ViewModel()
    viewControllerDelegate?.displaySomething(viewModel: viewModel)
  }
}
