//
//  ProjectListModels.swift
//  CleanSwift(VIP)
//
//  Created by Steve JobsOne on 4/18/20.
//  Copyright (c) 2020 Steve JobsOne. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProjectList {
  // MARK: Use cases
  
  enum Something {
    struct Request {
    }
    struct Response {
    }
    struct ViewModel {
    }
  }
}
