//
//  LoginPresenter.swift
//  CleanSwift(VIP)
//
//  Created by Steve JobsOne on 4/14/20.
//  Copyright (c) 2020 Steve JobsOne. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: View Loader

protocol LoginPresentationLogicDelegate {
    func login(response:Login.Response.LoginStatus)
    func presentError(error: Error)
    //MARK: Loader Delegate
     func showOrHideLoader(response:Login.Response.Loader)
}

class LoginPresenter: LoginPresentationLogicDelegate {
    weak var viewControllerDelegate: LoginDisplayLogicDelegate?

    
    func login(response: Login.Response.LoginStatus) {
        let viewModel = Login.ViewModel(success:response.success)
        viewControllerDelegate?.loginStatus(viewModel: viewModel)
    }
    
    // MARK: - loader presentation
    func showOrHideLoader(response:Login.Response.Loader) {
        print(response)
        let viewModel = ViewModel.init(showOrHide: response.ShowOrHidden)
        viewControllerDelegate?.loaderShowOrHidden(viewModel:viewModel)
    }
    
    // MARK: - alert show
    func presentError(error: Error) {
        switch error {
        case NetworkError.invalidURL:
            self.viewControllerDelegate?.alertShowWith(errorViewModel: ErrorViewModel.init(title: "Errot", message: "Check Your Domain", buttonTitles: ["ok"]))
            break
        case NetworkError.offline:
            self.viewControllerDelegate?.alertShowWith(errorViewModel: ErrorViewModel.init(title: "Errot", message: "Check Internet Connection", buttonTitles: ["ok"]))
            break
        default:
            break
        }
    }
    
}
