//
//  LoginModels.swift
//  CleanSwift(VIP)
//
//  Created by Steve JobsOne on 4/14/20.
//  Copyright (c) 2020 Steve JobsOne. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {
  // MARK: Use cases
    
    // MARK: Login request
    
    struct Request {
          var userID: String?
          var password: String?
    }
    
     // MARK: Login Response
    
    struct Response {
        
        var success : Bool
        
        struct SignIn: Codable {
            let access_token: String
            let token_type: String
            let expiredAt: Double
        }

        struct SignInData: Codable {
            let time: String?
            let message: String?
            let uri: String?
            let errors: SignInErrors?
        }

        struct SignInErrors: Codable {
            let password: String?
            let emailID: String?
        }
        
    }
    
    // MARK: Login ViewModel
    
    struct ViewModel {
        var success: Bool
        
    }
}
