//
//  LoginInteractor.swift
//  CleanSwift(VIP)
//
//  Created by Steve JobsOne on 4/14/20.
//  Copyright (c) 2020 Steve JobsOne. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogicDelegate {
    func loginRequestWith(request: Login.Request)
}

protocol LoginDataStoreDelegate {
    var name: String { get }
}

class LoginInteractor: LoginBusinessLogicDelegate,LoginDataStoreDelegate,LoginWarkerDelegate {
    
    var presenterDelegate: LoginPresentationLogicDelegate?
  
    var worker: LoginWorker?
    var name: String = "szdfs"
    
    // MARK: Do something
    
    func loginRequestWith(request: Login.Request) {
        worker = LoginWorker()
        worker?.loginWarkerDelegate = self
        worker?.loginWith(request: request)
    }
    
    // MARK: - LoginWarkerDelegate
    
    func loaderWillShow(flag: Bool) {
        switch flag {
        case true:
            self.presenterDelegate?.showOrHideLoader(response: Login.Response.Loader.init(ShowOrHidden: true))
            break
        default:
             self.presenterDelegate?.showOrHideLoader(response: Login.Response.Loader.init(ShowOrHidden: false))
            break
        }
    }
    
    //MARK: presentError
    func presentError(error: Error) {
        self.presenterDelegate?.presentError(error: error)
    }
    
    func loginResponse(response: Login.Response.SignIn) {
        Token.shared.accessToken = response.access_token
        self.presenterDelegate?.login(response: Login.Response.LoginStatus(success: true))
    }
}
